theme: jekyll-theme-cayman
title: Welcome to Cody Berlin's SNHU ePortfolio
description: A collection of projects demonstrating growth in Software Design & Engineering, Algorithms & Data Structures, and Databases. 
